services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 30s
      retries: 5

  mongodb:
    image: mongo:latest
    container_name: mongo-container
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.runCommand('ping')" ]
      interval: 30s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
  mongo-data: